"use client";
import { useEffect,useRef,useState } from "react";
import {demoScenarios,simulateAutomation,type DemoScenario} from "@/lib/terraqo/automation-demo";
import {ExperienceCta,ExperienceShell,Reveal} from "./public-experience";
import s from "./public-experience.module.css";
export function AutomationSimulator(){
  const [scenario,setScenario]=useState<DemoScenario>("worklog");const [condition,setCondition]=useState(true);const [progress,setProgress]=useState(0);const [running,setRunning]=useState(false);
  const timer=useRef<ReturnType<typeof setInterval>|null>(null);
  useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);},[]);
  const trace=simulateAutomation(scenario,condition);
  function reset(){if(timer.current)clearInterval(timer.current);setRunning(false);setProgress(0);}
  function run(){reset();if(matchMedia("(prefers-reduced-motion: reduce)").matches){setProgress(trace.length);return;}setRunning(true);let count=0;timer.current=setInterval(()=>{count++;setProgress(count);if(count>=trace.length){if(timer.current)clearInterval(timer.current);setRunning(false);}},650);}
  return <ExperienceShell eyebrow="Automatización" title="El siguiente paso puede empezar solo." intro="Convierte un evento del trabajo en una acción con responsable y registro. Prueba la lógica antes de decidir qué necesita tu operación."><Reveal><section className={s.simulator} aria-label="Simulador de automatización"><div className={s.config}><p className={s.eyebrow}>Configura un ejemplo</p><h2>Cuando sucede esto…</h2><label>Evento de inicio<select value={scenario} onChange={e=>{reset();setScenario(e.target.value as DemoScenario);}}>{Object.entries(demoScenarios).map(([key,flow])=><option value={key} key={key}>{flow.label}</option>)}</select></label><label><input type="checkbox" checked={condition} onChange={e=>{reset();setCondition(e.target.checked);}}/>{demoScenarios[scenario].condition}</label><p className={s.disclaimer}>Desmarca la condición para comprobar cuándo una regla debe detenerse.</p><button type="button" className={s.primary} disabled={running} onClick={run}>{running?"Ejecutando ejemplo…":progress?"Volver a simular":"Simular este flujo"}<span aria-hidden>→</span></button><p className={s.disclaimer}>Demostración local. No envía mensajes, modifica cuentas ni activa automatizaciones en tu workspace.</p></div><div className={s.trace}><h3>Así avanza la regla</h3><p>Evento → condición → acción → registro</p><ol>{trace.map((step,index)=><li key={step.title} data-done={progress>index}><strong>{step.title}</strong><small>{step.detail}</small></li>)}</ol><p role="status" className={s.status}>{running?`Paso ${progress+1} de ${trace.length}`:progress?condition?"Ejemplo completado. La acción y su registro forman parte del mismo recorrido.":"Flujo detenido correctamente. No se ejecutó ninguna acción.":"Selecciona un evento y ejecuta el ejemplo para ver el resultado."}</p></div></section></Reveal><Reveal><div className={s.notes}><section><h2>Reglas que respetan el contexto.</h2><p>Define quién recibe una notificación, qué condición la activa y en qué espacio se registra. Los responsables y permisos deben conservarse durante todo el recorrido.</p></section><section><h2>Capacidad acorde con tu operación.</h2><p>La disponibilidad del módulo y sus límites dependen del plan de empresa. Revisa el alcance antes de contratar; las integraciones específicas requieren una evaluación.</p></section></div></Reveal><ExperienceCta title="Diseña el primer flujo de tu equipo." description="Cuéntanos qué seguimiento repites y qué resultado necesitas. Te ayudamos a definir el evento, la condición y la acción." href="/contacto?asunto=automatizacion-terraqo" label="Evaluar mi operación"/></ExperienceShell>;
}
