"use client";
import Link from "next/link";
import {useState} from "react";
import {getDefaultModulesForTier,terraqoModules} from "@/lib/workspace";
import {ExperienceCta,ExperienceShell,Reveal} from "./public-experience";
import s from "./public-experience.module.css";
type Plan={name:string;price:string;description:string;features:string[];href:string;cta:string};
const personal:Plan[]=[
  {name:"Free",price:"Sin costo",description:"Empieza a construir tu identidad y participa en la comunidad profesional.",features:["Perfil profesional independiente","Registro de experiencia","Acceso inicial a Terraqo"],href:"/registro",cta:"Crear mi cuenta"},
  {name:"Terraqo Pro",price:"Desde S/ 29",description:"Amplía las capacidades de tu trayectoria y las herramientas de tu perfil.",features:["Plan personal, sin empresa vinculada","Herramientas según el plan contratado","Acompañamiento en la activación"],href:"/contacto?asunto=terraqo-pro",cta:"Consultar activación"},
];
const business:Plan[]=[
  {name:"Workspace Lite",price:"Desde S/ 199",description:"Centraliza los primeros procesos comerciales y proyectos de tu equipo.",features:["CRM y seguimiento comercial","Gestión de proyectos","Permisos por workspace"],href:"/contacto?asunto=workspace-lite",cta:"Elegir Workspace Lite"},
  {name:"Professional",price:"Consultar",description:"Conecta la operación con documentos, automatización y comunicación.",features:["Todo el alcance de Workspace Lite","Automatización y documentos","Sitio público y herramientas comerciales"],href:"/contacto?asunto=workspace-professional",cta:"Evaluar Professional"},
  {name:"Enterprise",price:"A medida",description:"Define el alcance para una operación con múltiples equipos e integraciones.",features:["Analítica ejecutiva","Capacidades del plan Premium","Alcance y acompañamiento acordados"],href:"/contacto?asunto=workspace-enterprise",cta:"Diseñar mi solución"},
];
const tiers=["BASIC","PROFESSIONAL","PREMIUM","ENTERPRISE"] as const;
export function MembershipExplorer(){
  const [audience,setAudience]=useState<"personal"|"business">("personal");
  const plans=audience==="personal"?personal:business;
  return <ExperienceShell eyebrow="Membresías" title="El espacio adecuado para tu siguiente etapa." intro="Tu trayectoria personal y la operación de tu empresa tienen necesidades distintas. Elige desde dónde quieres empezar y compara el alcance."><div className={s.segmented} aria-label="Tipo de membresía"><button type="button" aria-pressed={audience==="personal"} onClick={()=>setAudience("personal")}>Soy profesional</button><button type="button" aria-pressed={audience==="business"} onClick={()=>setAudience("business")}>Somos empresa</button></div><div key={audience} className={s.stageBody} style={{paddingTop:0}}><div className={s.plans} style={audience==="personal"?{gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,320px),1fr))"}:undefined}>{plans.map(plan=><article className={s.plan} key={plan.name}><h2>{plan.name}</h2><p>{plan.description}</p><div className={s.price}>{plan.price}{plan.price.startsWith("Desde")&&<small> / mes</small>}</div><ul>{plan.features.map(feature=><li key={feature}>{feature}</li>)}</ul><Link className={s.primary} href={plan.href}>{plan.cta}<span aria-hidden>↗</span></Link></article>)}</div></div><p className={s.disclaimer}>Los importes publicados son referenciales de entrada. La propuesta confirma precio total, impuestos, límites y condiciones antes de contratar. No se realizará ningún cobro desde esta comparación.</p>{audience==="business"?<details className={s.comparison}><summary>Comparar todos los módulos y niveles de empresa</summary><div className={s.tableScroll} tabIndex={0} role="region" aria-label="Comparación de módulos por plan"><table><caption>Disponibilidad por nivel del producto. Los módulos deben activarse en la suscripción del workspace; las integraciones a medida se acuerdan por separado.</caption><thead><tr><th scope="col">Módulo</th>{["Lite","Professional","Premium","Enterprise"].map(t=><th scope="col" key={t}>{t}</th>)}</tr></thead><tbody>{terraqoModules.filter(module=>module.code!=="BUILDERS").map(module=><tr key={module.code}><th scope="row">{module.label}</th>{tiers.map(tier=><td key={tier}>{getDefaultModulesForTier(tier).includes(module.code)?"Disponible":"—"}</td>)}</tr>)}</tbody></table></div></details>:<Reveal><div className={s.notes}><section><h2>Tu perfil es independiente.</h2><p>Puedes desarrollar tu trayectoria sin pertenecer al workspace de una empresa. Las relaciones laborales agregan contexto y conservan los permisos de cada parte.</p></section><section><h2>Publicar sigue siendo tu decisión.</h2><p>El perfil y su vista previa para redes se actualizan con tu información pública. Los documentos privados y la operación de una empresa conservan sus controles de acceso.</p></section></div></Reveal>}<ExperienceCta title="¿Qué necesita tu siguiente etapa?" description="Revisamos contigo el número de personas, los procesos y las capacidades necesarias para recomendar un alcance concreto." href="/contacto?asunto=asesoria-membresias" label="Hablar con Terraqo"/></ExperienceShell>;
}
