"use client";
import {useState} from "react";
import Link from "next/link";
import s from "./public-experience.module.css";
import {legalOperator as op} from "@/lib/terraqo/legal";
export function PublicInquiry({subject}:{subject:string}){
 const [name,setName]=useState("");const [message,setMessage]=useState("");const [draft,setDraft]=useState<string|null>(null);
 return <div className="tq-contact-surface"><p><strong>Terraqo, producto de {op.name} · RUC {op.ruc}</strong><br/>{op.address}<br/><a href={`mailto:${op.email}`}>{op.email}</a> · <a href={op.phoneHref}>{op.phone}</a></p><p>Para una queja o reclamo formal, utiliza el <Link href="/libro-de-reclamaciones">Libro de Reclamaciones integrado</Link>. Para comprar una membresía, <Link href="/membresias">elige tu plan y paga dentro del portal</Link>.</p><form onSubmit={event=>{event.preventDefault();setDraft(`https://wa.me/51925912607?text=${encodeURIComponent(`Hola, soy ${name.trim()}. Consulta sobre ${subject}.\n\n${message.trim()}`)}`);}}><label>Tu nombre<input required maxLength={120} autoComplete="name" value={name} onChange={event=>{setDraft(null);setName(event.target.value);}}/></label><label>¿Qué necesitas resolver?<textarea required minLength={10} maxLength={2000} value={message} onChange={event=>{setDraft(null);setMessage(event.target.value);}}/></label><p>Consulta: <strong>{subject}</strong></p><p>Preparamos tu mensaje para atención al cliente. Podrás revisarlo en WhatsApp antes de enviarlo. No es necesario usar WhatsApp para contratar ni reclamar.</p><button className={s.primary} type="submit">Preparar mi consulta →</button>{draft&&<div role="status"><p>Tu mensaje está preparado.</p><a className={s.primary} href={draft} target="_blank" rel="noopener noreferrer">Continuar por WhatsApp ↗</a></div>}</form></div>;
}
