"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight, BadgeCheck, BellRing, BriefcaseBusiness, Check, FileCheck2, Network, ShieldCheck, UserRoundCheck, Workflow } from "lucide-react";
import styles from "./terraqo-home-experience.module.css";

const views = [
  { id:"identity", label:"Identidad", icon:UserRoundCheck, title:"Una trayectoria que se actualiza con trabajo real.", copy:"Experiencias, bitácoras, documentos y validaciones bajo control del profesional.", stats:["12 registros","5 experiencias","4 validaciones"] },
  { id:"workspace", label:"Workspace", icon:BriefcaseBusiness, title:"La operación mantiene contexto y responsables.", copy:"Proyectos, equipos, archivos y conversaciones aislados dentro de cada empresa.", stats:["17 proyectos","22 profesionales","148 evidencias"] },
  { id:"automation", label:"Automatización", icon:Workflow, title:"Los procesos avanzan sin seguimiento manual.", copy:"Eventos y acciones conectan CRM, proyectos, talento y comunicación según el plan.", stats:["5 flujos","1.000 ejecuciones","Auditoría activa"] },
] as const;
const signals = [["AB","Antonio Bravo","Replanteo de luminarias"],["YD","Yamila Denis","Levantamiento validado"],["IC","ICC Topografía","Oportunidad publicada"]];

export function TerraqoHomeExperience() {
  const [active,setActive] = useState<(typeof views)[number]["id"]>("identity");
  const current = views.find((item)=>item.id===active) ?? views[0];
  const ActiveIcon=current.icon;
  return <div className={styles.site}>
    <section className={styles.hero}><div className={styles.heroCopy}><span className={styles.eyebrow}>La red del trabajo real</span><h1>Tu trabajo deja huella.<em>Terraqo la convierte en confianza.</em></h1><p>Personas, empresas, proyectos y evidencia conectados en una infraestructura profesional que respeta la propiedad de cada dato.</p><div className={styles.actions}><Link href="/registro">Crear mi identidad <ArrowRight /></Link><Link href="/producto">Explorar el producto</Link></div><div className={styles.facts}><span><Check /> Perfil independiente</span><span><Check /> Evidencia verificable</span><span><Check /> Workspace privado</span></div></div><div className={styles.signalBoard}><header><span>Actividad conectada</span><b>En vivo</b></header>{signals.map(([initials,name,event],index)=><article key={name}><i>{initials}</i><div><b>{name}</b><span>{event}</span></div><small>0{index+1}</small></article>)}<footer><ShieldCheck /> Sólo se comparte información autorizada.</footer></div></section>
    <section className={styles.statement}><span>No es otro directorio</span><h2>Un CV dice lo que hiciste.<em>Terraqo puede demostrarlo.</em></h2><p>El trabajo deja de quedar aislado en documentos y conversaciones. Cada resultado puede conservar proyecto, autor, fecha, evidencia y validación.</p></section>
    <section className={styles.product}><div className={styles.sectionIntro}><span>Producto conectado</span><h2>Tres espacios. Una sola fuente de contexto.</h2><p>Selecciona una vista para entender cómo se relacionan sin mezclar propiedad ni permisos.</p></div><div className={styles.productShell}><nav>{views.map(({id,label,icon:Icon})=><button key={id} type="button" aria-pressed={active===id} onClick={()=>setActive(id)}><Icon />{label}</button>)}</nav><div className={styles.productView} key={active}><div className={styles.productIcon}><ActiveIcon /></div><div><small>{current.label}</small><h3>{current.title}</h3><p>{current.copy}</p><div className={styles.stats}>{current.stats.map((stat)=><span key={stat}>{stat}</span>)}</div><Link href={active==="automation"?"/automatizacion":active==="workspace"?"/plataforma":"/producto"}>Ver capacidad completa <ArrowRight /></Link></div></div></div></section>
    <section className={styles.networkSection}><div className={styles.sectionIntro}><span>Red profesional</span><h2>Conecta con capacidad demostrada, no con ruido.</h2><p>Descubre profesionales y empresas por experiencia visible, especialidad, disponibilidad y trabajo documentado.</p></div><div className={styles.people}>{signals.map(([initials,name,event],index)=><article key={name}><header><i>{initials}</i><div><h3>{name}</h3><p>{index===2?"Empresa verificada":"Profesional disponible"}</p></div>{index<2&&<BadgeCheck />}</header><span>{event}</span><footer><Link href="/red">Explorar en la red</Link><ArrowRight /></footer></article>)}</div></section>
    <section className={styles.trust}><div><span>Confianza por capas</span><h2>No toda información tiene el mismo peso.</h2><p>Terraqo diferencia lo declarado de aquello revisado, respaldado o confirmado.</p><Link href="/plataforma">Conocer la arquitectura <ArrowRight /></Link></div><ol>{[["01","Declarado"],["02","Revisado por Terraqo"],["03","Respaldado por supervisor"],["04","Confirmado por empresa"]].map(([n,label])=><li key={n}><b>{n}</b><span>{label}</span><FileCheck2 /></li>)}</ol></section>
    <section className={styles.automation}><BellRing /><div><span>Automatización por suscripción</span><h2>El seguimiento ocurre mientras el equipo trabaja.</h2><p>Professional activa alertas y asignaciones; Premium suma condiciones; Enterprise incorpora integraciones y gobierno avanzado.</p></div><Link href="/automatizacion">Comparar capacidades <ArrowRight /></Link></section>
    <section className={styles.closing}><Network /><h2>Construye una identidad profesional que crece mientras trabajas.</h2><p>Trabajo real. Contexto compartido. Confianza verificable.</p><div className={styles.actions}><Link href="/registro">Crear cuenta <ArrowRight /></Link><Link href="/membresias">Ver membresías</Link></div></section>
  </div>;
}
