import Link from "next/link";
import { BadgeCheck, BriefcaseBusiness, Clock3, Coins, ShieldAlert, UsersRound } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { prisma } from "@/lib/prisma";
import { requireAdminPage } from "@/lib/server/admin-page-auth";
import { configureWorkRelationshipAction, reviewAttendanceAction, reviewAttendanceAdjustmentAction } from "@/lib/server/jornada-actions";
import { formatMinutes } from "@/lib/terraqo/jornada";
import { getSessionTerraqoWorkspaceId } from "@/lib/terraqo/workspace-scope";

export const dynamic = "force-dynamic";

export default async function AdminJourneysPage({ searchParams }: { searchParams: Promise<{ member?: string; success?: string }> }) {
  const params = await searchParams;
  await requireAdminPage(["ADMIN", "SUPER_ADMIN"]);
  const workspaceId = await getSessionTerraqoWorkspaceId();
  const members = await prisma.terraqoWorkspaceMember.findMany({
    where: { workspaceId, active: true, role: "PROFESSIONAL" },
    include: {
      user: { select: { name: true, email: true, image: true } },
      workRelationship: { include: { schedules: { where: { effectiveTo: null }, orderBy: { effectiveFrom: "desc" }, take: 1 }, compensationPolicies: { where: { source: "COMPANY", effectiveTo: null }, orderBy: { effectiveFrom: "desc" }, take: 1 } } },
    },
    orderBy: { user: { name: "asc" } },
  });
  const selected = members.find((member) => member.id === params.member) || members[0] || null;
  const [approvals, adjustments] = await Promise.all([
    prisma.terraqoAttendanceApproval.findMany({ where: { workRelationship: { workspaceId }, status: "PENDING" }, include: { workRelationship: { include: { member: { include: { user: { select: { name: true } } } } } } }, orderBy: { createdAt: "asc" }, take: 20 }),
    prisma.terraqoAttendanceAdjustment.findMany({ where: { workRelationship: { workspaceId }, status: "REQUESTED" }, include: { workRelationship: { include: { member: { include: { user: { select: { name: true } } } } } } }, orderBy: { createdAt: "asc" }, take: 20 }),
  ]);
  const schedule = selected?.workRelationship?.schedules[0];
  const policy = selected?.workRelationship?.compensationPolicies[0];

  return (
    <main className="space-y-6">
      <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Operación verificable</p><h1 className="mt-2 font-display text-4xl font-bold">Jornadas y relaciones laborales</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Configura reglas privadas por colaborador, revisa horas adicionales e incidencias sin alterar las marcas originales.</p></div><div className="flex gap-2"><span className="rounded-md bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800">{approvals.length} jornadas pendientes</span><span className="rounded-md bg-rose-50 px-3 py-2 text-xs font-bold text-rose-800">{adjustments.length} incidencias</span></div></header>
      {params.success ? <div role="status" className="rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">Cambios guardados con trazabilidad.</div> : null}

      <section className="grid gap-5 xl:grid-cols-[320px_minmax(0,1fr)]">
        <aside className="rounded-lg border bg-white p-4"><h2 className="flex items-center gap-2 font-display text-lg font-bold"><UsersRound className="h-5 w-5 text-primary" />Colaboradores</h2><div className="mt-4 grid gap-2">{members.map((member) => <Link key={member.id} href={`/admin/jornadas?member=${member.id}`} className={`rounded-md border px-3 py-3 transition ${selected?.id === member.id ? "border-primary bg-primary/5" : "hover:bg-muted/50"}`}><strong className="block text-sm">{member.user.name || member.user.email}</strong><span className="mt-1 block text-xs text-muted-foreground">{member.title || "Profesional"}</span><span className={`mt-2 inline-flex rounded-full px-2 py-1 text-[10px] font-bold ${member.workRelationship?.status === "ACTIVE" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-800"}`}>{member.workRelationship?.status === "ACTIVE" ? "Configurado" : "Pendiente"}</span></Link>)}{!members.length ? <p className="text-sm text-muted-foreground">No hay profesionales activos en este workspace.</p> : null}</div></aside>

        {selected ? <form action={configureWorkRelationshipAction} className="rounded-lg border bg-white p-5"><input type="hidden" name="memberId" value={selected.id} /><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Relación laboral</p><h2 className="mt-1 font-display text-2xl font-bold">{selected.user.name || selected.user.email}</h2><p className="mt-1 text-sm text-muted-foreground">{selected.user.email}</p></div>{selected.workRelationship?.confirmedAt ? <span className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><BadgeCheck className="h-4 w-4" />Confirmada</span> : null}</div>
          <fieldset className="mt-6 grid gap-4 sm:grid-cols-2"><legend className="mb-3 flex items-center gap-2 font-display text-lg font-bold"><BriefcaseBusiness className="h-5 w-5 text-primary" />Condiciones generales</legend><label className="grid gap-1.5 text-sm font-semibold">Cargo<Input value={selected.title || "Profesional"} readOnly /></label><label className="grid gap-1.5 text-sm font-semibold">Área<Input name="area" defaultValue={selected.workRelationship?.area || ""} required /></label><label className="grid gap-1.5 text-sm font-semibold">Tipo de contrato<Input name="contractType" defaultValue={selected.workRelationship?.contractType || ""} placeholder="Plazo indeterminado" required /></label><label className="grid gap-1.5 text-sm font-semibold">Modalidad<Input name="modality" defaultValue={selected.workRelationship?.modality || ""} placeholder="Presencial" required /></label><label className="grid gap-1.5 text-sm font-semibold">Sede<Input name="workSite" defaultValue={selected.workRelationship?.workSite || ""} required /></label><label className="grid gap-1.5 text-sm font-semibold">Fecha de inicio<Input name="startDate" type="date" defaultValue={selected.workRelationship?.startDate?.toISOString().slice(0, 10) || ""} required /></label></fieldset>
          <fieldset className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><legend className="mb-3 flex items-center gap-2 font-display text-lg font-bold"><Clock3 className="h-5 w-5 text-primary" />Horario esperado</legend><label className="grid gap-1.5 text-sm font-semibold">Entrada<Input name="startTime" type="time" defaultValue={schedule?.startTime || "08:00"} required /></label><label className="grid gap-1.5 text-sm font-semibold">Salida<Input name="endTime" type="time" defaultValue={schedule?.endTime || "17:00"} required /></label><label className="grid gap-1.5 text-sm font-semibold">Refrigerio (min)<Input name="breakMinutes" type="number" min="0" max="240" defaultValue={schedule?.breakMinutes ?? 60} required /></label><label className="grid gap-1.5 text-sm font-semibold">Tolerancia (min)<Input name="toleranceMinutes" type="number" min="0" max="120" defaultValue={schedule?.toleranceMinutes ?? 10} required /></label><div className="sm:col-span-2 lg:col-span-4"><span className="block text-sm font-semibold">Días laborables</span><div className="mt-2 flex flex-wrap gap-2">{[[1,"Lun"],[2,"Mar"],[3,"Mié"],[4,"Jue"],[5,"Vie"],[6,"Sáb"]].map(([value,label]) => <label key={value} className="flex min-h-11 items-center gap-2 rounded-md border px-3 text-sm"><input type="checkbox" name="workDays" value={value} defaultChecked={(schedule?.workDays || [1,2,3,4,5]).includes(Number(value))} />{label}</label>)}</div></div><label className="grid gap-1.5 text-sm font-semibold">Entrada sábado<Input name="saturdayStartTime" type="time" defaultValue={schedule?.saturdayStartTime || ""} /></label><label className="grid gap-1.5 text-sm font-semibold">Salida sábado<Input name="saturdayEndTime" type="time" defaultValue={schedule?.saturdayEndTime || ""} /></label><label className="grid gap-1.5 text-sm font-semibold">Refrigerio sábado<Input name="saturdayBreakMinutes" type="number" min="0" defaultValue={schedule?.saturdayBreakMinutes ?? 0} /></label></fieldset>
          <fieldset className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><legend className="mb-3 flex items-center gap-2 font-display text-lg font-bold"><Coins className="h-5 w-5 text-primary" />Compensación privada</legend><label className="grid gap-1.5 text-sm font-semibold">Monto base (PEN)<Input name="baseAmount" type="number" min="1" step="0.01" defaultValue={policy ? Number(policy.baseAmount) : ""} required /></label><label className="grid gap-1.5 text-sm font-semibold">Frecuencia<select name="frequency" defaultValue={policy?.frequency || "MONTHLY"} className="h-10 rounded-md border bg-background px-3"><option value="MONTHLY">Mensual</option><option value="DAILY">Diaria</option><option value="HOURLY">Por hora</option></select></label><label className="grid gap-1.5 text-sm font-semibold">Día de pago<Input name="paymentDay" type="number" min="1" max="31" defaultValue={policy?.paymentDay ?? 28} required /></label><label className="grid gap-1.5 text-sm font-semibold">Hora adicional referencial<Input name="hourlyReferenceAmount" type="number" min="0.01" step="0.01" defaultValue={policy?.hourlyReferenceAmount ? Number(policy.hourlyReferenceAmount) : ""} required /></label></fieldset>
          <div className="mt-6 flex flex-col gap-3 rounded-md bg-blue-50 p-4 text-xs leading-5 text-blue-900 sm:flex-row sm:items-center sm:justify-between"><p>El guardado cierra la vigencia anterior y crea una nueva versión. Las estimaciones no sustituyen una boleta de pago.</p><Button type="submit" className="min-h-11 shrink-0">Guardar y confirmar</Button></div>
        </form> : null}
      </section>

      <section className="grid gap-5 xl:grid-cols-2">
        <article className="rounded-lg border bg-white p-5"><h2 className="flex items-center gap-2 font-display text-xl font-bold"><Clock3 className="h-5 w-5 text-amber-600" />Horas adicionales por revisar</h2><div className="mt-4 grid gap-3">{approvals.map((approval) => <form key={approval.id} action={reviewAttendanceAction} className="rounded-md border p-4"><input type="hidden" name="approvalId" value={approval.id} /><div className="flex items-start justify-between gap-3"><div><strong className="text-sm">{approval.workRelationship.member.user.name || "Profesional"}</strong><p className="mt-1 text-xs text-muted-foreground">{formatMinutes(approval.regularMinutes)} regulares · {formatMinutes(approval.additionalDetectedMinutes)} adicionales</p></div><span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-800">Pendiente</span></div><div className="mt-3 grid gap-3 sm:grid-cols-[180px_1fr_auto]"><label className="grid gap-1 text-xs font-semibold">Minutos aprobados<Input name="additionalApprovedMinutes" type="number" min="0" max={approval.additionalDetectedMinutes} defaultValue={approval.additionalDetectedMinutes} /></label><label className="grid gap-1 text-xs font-semibold">Observación<Input name="reviewNote" /></label><Button type="submit" variant="outline" className="min-h-10 self-end">Resolver</Button></div></form>)}{!approvals.length ? <p className="rounded-md bg-muted/40 p-4 text-sm text-muted-foreground">No hay jornadas pendientes.</p> : null}</div></article>
        <article className="rounded-lg border bg-white p-5"><h2 className="flex items-center gap-2 font-display text-xl font-bold"><ShieldAlert className="h-5 w-5 text-rose-600" />Incidencias solicitadas</h2><div className="mt-4 grid gap-3">{adjustments.map((adjustment) => <form key={adjustment.id} action={reviewAttendanceAdjustmentAction} className="rounded-md border p-4"><input type="hidden" name="adjustmentId" value={adjustment.id} /><div><strong className="text-sm">{adjustment.workRelationship.member.user.name || "Profesional"}</strong><p className="mt-1 text-xs text-muted-foreground">{adjustment.type.replaceAll("_", " ")}</p><p className="mt-3 text-sm">{adjustment.reason}</p></div><label className="mt-3 grid gap-1 text-xs font-semibold">Respuesta<Textarea name="reviewNote" maxLength={1000} /></label><div className="mt-3 flex gap-2"><Button type="submit" name="decision" value="APPROVED" variant="outline">Aprobar</Button><Button type="submit" name="decision" value="REJECTED" variant="outline">Rechazar</Button></div></form>)}{!adjustments.length ? <p className="rounded-md bg-muted/40 p-4 text-sm text-muted-foreground">No hay incidencias pendientes.</p> : null}</div></article>
      </section>
    </main>
  );
}
